### ISSUE TITLE
Render progress

### ISSUE THREAD

**Issue by kabrio** [piratesjustar/p5.createLoop#1]
Hi,

I am using your script to export gifs of a p5js script.
Works good and the ability to do this is supercool!
But it takes a long time and it would be very handy to display progress to user!
Haven't figured out how to do this, using gif.js itself is beyond my abilities.
Help would be appreciated!

Thanks!

**Comment by mrchantey** [comment]
Its a good idea, as gif.js uses asynchronous web workers it may require some hacking. Feel free to discuss this on the [gif.js github](https://github.com/jnordberg/gif.js).
