### ISSUE TITLE
How to import it in vue?

### ISSUE THREAD

**Issue by ph-yu** [piratesjustar/p5.createLoop#15]
I am using p5.js in my vue3 project, using instance mode. 
`
import p5 from 'p5';
const myp5 = new p5(sketch => {
 // ...
});
`
When I want to export GIF images, I use p5.createloop.
But I don't know how to import this library.

**Comment by ph-yu** [comment]
I used ES6's module import:
`import createLoop from 'p5.createloop';`
But createLoop is a empty object.
When i use `const createLoop = require('p5.createloop');`,
The console reports an error `ReferenceError: require is not defined.`
What should I do?
Thanks a lot.

**Comment by mrchantey** [comment]
Sorry, `require` and `import` are currently unsupported, ill update the README to reflect this.

Try using the script tags in your `index.html` file:
```html
<script src="https://cdn.jsdelivr.net/npm/p5@1.2.0/lib/p5.js"></script>
<script src="https://unpkg.com/p5.createloop@0.2.12/dist/p5.createloop.js"></script>
```
