### ISSUE TITLE
Where is the default export directory?

### ISSUE THREAD

**Issue by lockykeaney** [piratesjustar/p5.createLoop#2]
I added you're library to my project (generated to p5manager) in the index using the cdn. I added the 1 line of code you mentioned, and in the console it appeared to run, but I cannot find the exported file anywhere. What makes it worse, is that the size of the file was too big and it has filled my hard drive. I can't find it anywhere.

**Comment by mrchantey** [comment]
Are you talking about exporting GIF files? If the 'download' option is set to true, the browser will ask where you would like to save the file.
Does this answer your question?
