### ISSUE TITLE
Add Callback Ability

### ISSUE THREAD

**Issue by xpluscal** [piratesjustar/p5.createLoop#30]
Instead of rendering to a page, it would be great if we could hook into the events when a gif is finished to e.g. upload it to a server.
Any ideas how to go about this? @mrchantey Thank you!

**Comment by xpluscal** [comment]
Hey @mrchantey any news on this?

**Comment by mrchantey** [comment]
Apologies for the delay, should work in `v0.3.1`, example:
```js
createLoop({
    gif: {
        onFinishRender: blob => console.log(blob.size)
    }
})
```
Let me know if you have any issues
