### ISSUE TITLE
GIF color rendition off

### ISSUE THREAD

**Issue by tonyrobots** [piratesjustar/p5.createLoop#9]
Here's an example, contrasting in-browser p5.js rendering on the left, and GIF output on the right (using default settings, but have tried different settings to no avail.)

Has anyone else encountered this, and do you have any suggestions?

Maybe this is an issue I should take up with the GIF rendering library, but I wonder if there's any other solution (including non-GIF animated output options, like video or APNG?
![Screenshot 2021-10-11 142133](https://user-images.githubusercontent.com/178870/136857360-4b721108-b2c7-4c4c-8879-50b919e5c5ca.png)
)

**Comment by tonyrobots** [comment]
Looks like it's the issue described [here ](https://github.com/jnordberg/gif.js/pull/45)and [here](https://github.com/jnordberg/gif.js/pull/46), and has been [fixed](https://github.com/jnordberg/gif.js/commit/92d27a02841339e202c75150dcf6fe5f4fa42ec5), but p5.createLoop is still using an older version.

**Comment by tonyrobots** [comment]
Nope, that wasn't it. As it turns out, the background color *behind* the canvas is affecting the color on the left. Creating the canvas in instance mode fixes the problem, so it's apparently a p5.js issue.

**Comment by mrchantey** [comment]
Wow yeah thats weird, maybe differences in how the color blending is happening? I'll close the issue for now because it doesnt look like its coming from this repo, but let me know if there turns out to be something I can do.
